### PR TITLE
SipDialogController: Protect against glare during reINVITE

### LINKED ISSUE #401: Crash on Session-Expires reINVITE glare
Scenario:
Session-Expires with `refresher=uas`
    
When client receives re-INVITE, it immediately sends BYE, and only then it responds with 481 to the INVITE.

This results in drachtio crash.

sipp script to reproduce: [uas-session-expires-glare.zip](https://github.com/user-attachments/files/18200346/uas-session-expires-glare.zip)

### PR DESCRIPTION
**Pull request by orgads**
Scenario:
Session-Expires with refresher=uas

When client receives re-INVITE, it immediately sends BYE, and only then it responds with 481 to the INVITE.

This results in drachtio crash.

Fixes #401

### CODE REVIEW

File: src/sip-dialog-controller.cpp [hunk 1]
```diff
@@ -1677,7 +1677,8 @@ namespace drachtio {
         std::shared_ptr<RIP> rip  ;
 
         nta_leg_t* leg = nta_leg_by_call_id(m_pController->getAgent(), sip->sip_call_id->i_id);
-        assert(leg) ;
+        if (!leg)
+          return 0;
```
Comment (davehorton) [inline src/sip-dialog-controller.cpp:1681]: could we have a log message here to indicate what has happened - ie the possibility of glare condition

Comment (orgads) [reply src/sip-dialog-controller.cpp:1681]: Sure

Comment (orgads) [reply src/sip-dialog-controller.cpp]: Done

**Review by davehorton — APPROVED** [review]
